"""
export/mp4_export.py — Trigger offline .mp4 render via Puppeteer + ffmpeg.

This module is the Python side of the export pipeline.  The actual rendering
happens in the browser (headless Chrome via Puppeteer captures frames from the
Three.js scene), and ffmpeg stitches frames into an .mp4.

How it works
------------
1. Python starts the WebSocket server (features already loaded).
2. Python launches Puppeteer via Node.js: `node export/record.js`
3. record.js opens the visualiser URL, connects via WS, plays at 1×, and
   saves each animation frame as a PNG into a temp directory.
4. Python waits for record.js to signal completion (via a sentinel file).
5. Python runs ffmpeg to assemble PNGs → .mp4 at config.EXPORT_FPS.

The Node.js script (export/record.js) is generated by this module if it
doesn't exist, so you don't need to maintain it separately.

Requirements
------------
- Node.js 20 + npm install puppeteer
- ffmpeg on PATH
"""

from __future__ import annotations
import asyncio
import shutil
import subprocess
import tempfile
import textwrap
from pathlib import Path

import sys
sys.path.insert(0, str(Path(__file__).parent.parent))
import config

RECORD_JS = Path(__file__).parent / "record.js"
EXPORT_DIR = config.PROJECT_ROOT / "export_frames"


def generate_record_js(ws_url: str, vis_url: str, frames_dir: Path, fps: int) -> None:
    """Write the Puppeteer recording script if it doesn't exist."""
    script = textwrap.dedent(f"""\
        /**
         * record.js — Puppeteer frame recorder for Strata.
         * Auto-generated by export/mp4_export.py — do not edit manually.
         */
        const puppeteer = require('puppeteer');
        const fs        = require('fs');
        const path      = require('path');

        const VIS_URL   = '{vis_url}';
        const WS_URL    = '{ws_url}';
        const OUT_DIR   = '{frames_dir}';
        const FPS       = {fps};
        const SENTINEL  = path.join(OUT_DIR, 'DONE');

        (async () => {{
          fs.mkdirSync(OUT_DIR, {{ recursive: true }});

          const browser = await puppeteer.launch({{
            headless: 'new',
            args: ['--no-sandbox', '--disable-setuid-sandbox',
                   '--window-size={config.EXPORT_WIDTH},{config.EXPORT_HEIGHT}'],
          }});

          const page = await browser.newPage();
          await page.setViewport({{ width: {config.EXPORT_WIDTH}, height: {config.EXPORT_HEIGHT} }});
          await page.goto(VIS_URL, {{ waitUntil: 'networkidle0' }});

          // Connect WebSocket and wait for 'ready'
          await page.evaluate((wsUrl) => {{
            return new Promise((resolve) => {{
              window.__ws = new WebSocket(wsUrl);
              window.__ws.onmessage = (e) => {{
                const msg = JSON.parse(e.data);
                if (msg.type === 'ready') resolve();
              }};
            }});
          }}, WS_URL);

          // Send play
          await page.evaluate(() => window.__ws.send(JSON.stringify({{ cmd: 'play' }})));

          let frameIdx = 0;
          let ended = false;

          await page.evaluate(() => {{
            window.__ended = false;
            window.__ws.addEventListener('message', (e) => {{
              const msg = JSON.parse(e.data);
              if (msg.type === 'ended') window.__ended = true;
            }});
          }});

          const interval = 1000 / FPS;
          while (!ended) {{
            const padded = String(frameIdx).padStart(6, '0');
            await page.screenshot({{ path: path.join(OUT_DIR, `frame_${{padded}}.png`) }});
            frameIdx++;
            ended = await page.evaluate(() => window.__ended);
            await new Promise(r => setTimeout(r, interval));
          }}

          await browser.close();
          fs.writeFileSync(SENTINEL, 'done');
          console.log(`[record] Captured ${{frameIdx}} frames → ${{OUT_DIR}}`);
        }})();
    """)
    RECORD_JS.write_text(script)
    print(f"[export] Generated {RECORD_JS}")


async def export_mp4(
    output_path: Path,
    vis_url: str = "http://localhost:5173",
    ws_url: str  = f"ws://{config.WS_HOST}:{config.WS_PORT}",
) -> Path:
    """
    Run the full Puppeteer → ffmpeg export pipeline.

    Parameters
    ----------
    output_path : Path  — where to write the final .mp4
    vis_url     : str   — URL of the running Three.js visualiser
    ws_url      : str   — URL of the Strata WebSocket server

    Returns
    -------
    Path to the written .mp4 file.
    """
    # Check dependencies
    if not shutil.which("node"):
        raise RuntimeError("Node.js not found on PATH. Install Node.js 20.")
    if not shutil.which("ffmpeg"):
        raise RuntimeError("ffmpeg not found on PATH. Install ffmpeg.")

    frames_dir = EXPORT_DIR
    frames_dir.mkdir(parents=True, exist_ok=True)
    sentinel   = frames_dir / "DONE"
    sentinel.unlink(missing_ok=True)

    generate_record_js(ws_url=ws_url, vis_url=vis_url,
                       frames_dir=frames_dir, fps=config.EXPORT_FPS)

    # Check Puppeteer installed
    pkg_json = Path(__file__).parent / "package.json"
    if not (Path(__file__).parent / "node_modules" / "puppeteer").exists():
        print("[export] Installing Puppeteer (first run only) …")
        pkg_json.write_text('{"dependencies":{"puppeteer":"*"}}')
        subprocess.run(["npm", "install"], cwd=Path(__file__).parent, check=True)

    # Launch Puppeteer recorder
    print(f"[export] Starting Puppeteer recorder → {frames_dir}")
    proc = await asyncio.create_subprocess_exec(
        "node", str(RECORD_JS),
        stdout=asyncio.subprocess.PIPE,
        stderr=asyncio.subprocess.PIPE,
    )

    # Poll for sentinel file
    import time
    timeout = 600  # 10 minutes max
    start   = time.monotonic()
    while not sentinel.exists():
        if time.monotonic() - start > timeout:
            proc.kill()
            raise TimeoutError("Puppeteer recording timed out after 10 minutes.")
        await asyncio.sleep(1.0)

    stdout, stderr = await proc.communicate()
    print(stdout.decode())
    if proc.returncode != 0:
        raise RuntimeError(f"Puppeteer failed:\n{stderr.decode()}")

    # Count frames
    pngs = sorted(frames_dir.glob("frame_*.png"))
    print(f"[export] Assembling {len(pngs)} frames → {output_path}")

    # Run ffmpeg
    ffmpeg_cmd = [
        "ffmpeg", "-y",
        "-framerate", str(config.EXPORT_FPS),
        "-i",         str(frames_dir / "frame_%06d.png"),
        "-c:v",       "libx264",
        "-pix_fmt",   "yuv420p",
        "-crf",       "18",
        "-preset",    "slow",
        str(output_path),
    ]
    result = subprocess.run(ffmpeg_cmd, capture_output=True, text=True)
    if result.returncode != 0:
        raise RuntimeError(f"ffmpeg failed:\n{result.stderr}")

    print(f"[export] Done → {output_path}")
    return output_path
