import { copyFile, mkdir, access, readdir, rm } from "node:fs/promises";
import { join } from "node:path";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const frontendDir = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const projectDir = resolve(frontendDir, "..");

await mkdir(resolve(frontendDir, "public"), { recursive: true });

// Copy features.json if it exists at the project root (generated by analysis pipeline)
const featuresSource = resolve(projectDir, "features.json");
const featuresDest = resolve(frontendDir, "public", "features.json");

try {
  await access(featuresSource);
  await copyFile(featuresSource, featuresDest);
  console.log(`Prepared frontend/public/features.json from ${featuresSource}`);
} catch {
  // Not present (e.g. CI without a pre-run analysis step) — leave existing file in place
  console.log("features.json not found at project root, skipping copy");
}

// Copy tracks.json if it exists
const tracksSource = resolve(projectDir, "frontend", "public", "tracks.json");
const tracksAlt = resolve(projectDir, "tracks.json");
const tracksDest = resolve(frontendDir, "public", "tracks.json");

for (const src of [tracksSource, tracksAlt]) {
  try {
    await access(src);
    await copyFile(src, tracksDest);
    console.log(`Prepared frontend/public/tracks.json from ${src}`);
    break;
  } catch {
    // try next
  }
}

// Copy top-level per-track feature JSON files. Internal caches such as
// features/_stem_cache are intentionally not published to GitHub Pages.
const featuresDir = resolve(projectDir, "features");
const featuresDirDest = resolve(frontendDir, "public", "features");

try {
  await access(featuresDir);
  await rm(featuresDirDest, { recursive: true, force: true });
  await mkdir(featuresDirDest, { recursive: true });
  const entries = await readdir(featuresDir);
  const jsonFiles = entries.filter((entry) => entry.endsWith(".json"));
  for (const entry of jsonFiles) {
    await copyFile(resolve(featuresDir, entry), resolve(featuresDirDest, entry));
  }
  console.log(`Copied features/*.json → public/features/ (${jsonFiles.length} files)`);
} catch {
  console.log("features/ directory not found at project root, skipping");
}

console.log("prepare-assets complete");
